-- MySQL Script generated by MySQL Workbench
-- Mon Apr 27 00:13:19 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ecommDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ecommDB` ;

-- -----------------------------------------------------
-- Schema ecommDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecommDB` DEFAULT CHARACTER SET utf8 ;
USE `ecommDB` ;

-- -----------------------------------------------------
-- Table `ecommDB`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommDB`.`category` ;

CREATE TABLE IF NOT EXISTS `ecommDB`.`category` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommDB`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommDB`.`role` ;

CREATE TABLE IF NOT EXISTS `ecommDB`.`role` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommDB`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommDB`.`user` ;

CREATE TABLE IF NOT EXISTS `ecommDB`.`user` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(150) NOT NULL,
  `pasword` VARCHAR(120) NOT NULL,
  `username` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommDB`.`user_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommDB`.`user_role` ;

CREATE TABLE IF NOT EXISTS `ecommDB`.`user_role` (
  `user_id` BIGINT NOT NULL,
  `role_id` BIGINT NOT NULL,
  PRIMARY KEY (`user_id`, `role_id`),
  CONSTRAINT `fk_user_has_role_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `ecommDB`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_role_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `ecommDB`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommDB`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommDB`.`product` ;

CREATE TABLE IF NOT EXISTS `ecommDB`.`product` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NOT NULL,
  `discount` DOUBLE NOT NULL,
  `image` VARCHAR(255) NOT NULL,
  `price` DOUBLE NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `stock` INT NOT NULL,
  `special_price` DOUBLE NOT NULL,
  `category_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  CONSTRAINT `fk_product_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `ecommDB`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommDB`.`cart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommDB`.`cart` ;

CREATE TABLE IF NOT EXISTS `ecommDB`.`cart` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `total_price` DOUBLE NOT NULL,
  `user_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_cart_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `ecommDB`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommDB`.`cart_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommDB`.`cart_item` ;

CREATE TABLE IF NOT EXISTS `ecommDB`.`cart_item` (
  `id` BIGINT NOT NULL,
  `discount` DOUBLE NOT NULL,
  `product_price` DOUBLE NOT NULL,
  `quantity` INT NOT NULL,
  `cart_id` BIGINT NOT NULL,
  `product_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_product_has_cart_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `ecommDB`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_has_cart_cart1`
    FOREIGN KEY (`cart_id`)
    REFERENCES `ecommDB`.`cart` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommDB`.`payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommDB`.`payment` ;

CREATE TABLE IF NOT EXISTS `ecommDB`.`payment` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `method` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `method_UNIQUE` (`method` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommDB`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommDB`.`order` ;

CREATE TABLE IF NOT EXISTS `ecommDB`.`order` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `date` DATE NOT NULL,
  `status` VARCHAR(255) NOT NULL,
  `total_amount` DOUBLE NOT NULL,
  `payment_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_order_payment1`
    FOREIGN KEY (`payment_id`)
    REFERENCES `ecommDB`.`payment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommDB`.`order_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommDB`.`order_item` ;

CREATE TABLE IF NOT EXISTS `ecommDB`.`order_item` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `discount` DOUBLE NOT NULL,
  `product_price` DOUBLE NOT NULL,
  `quantity` DOUBLE NOT NULL,
  `order_id` BIGINT NOT NULL,
  `product_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_order_has_product_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `ecommDB`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_has_product_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `ecommDB`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommDB`.`adress`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommDB`.`adress` ;

CREATE TABLE IF NOT EXISTS `ecommDB`.`adress` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `building_name` VARCHAR(255) NOT NULL,
  `city` VARCHAR(255) NOT NULL,
  `country` VARCHAR(255) NOT NULL,
  `pincode` VARCHAR(255) NOT NULL,
  `state` VARCHAR(255) NOT NULL,
  `street` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommDB`.`user_adress`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommDB`.`user_adress` ;

CREATE TABLE IF NOT EXISTS `ecommDB`.`user_adress` (
  `adress_id` BIGINT NOT NULL,
  `user_id` BIGINT NOT NULL,
  CONSTRAINT `fk_adress_has_user_adress1`
    FOREIGN KEY (`adress_id`)
    REFERENCES `ecommDB`.`adress` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_adress_has_user_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `ecommDB`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
