spring.application.name=backend

# LANGUAGE
spring.web.locale=en_US
spring.web.locale-resolver=fixed

# SPRING SECURITY
spring.security.user.name=admin
spring.security.user.password=admin123

# SERVICES
image.base.url=http://localhost:8080/images
frontend.url=http://localhost:5173/
project.image=images/

# JWT
spring.app.jwtSecret=SecretKeyForJWTGeneration000012324214u3b248bf2
spring.app.jwtExpirationMs=300000000
spring.ecom.app.jwtCookieName=ecomm-cookie

# MYSQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/ecomm?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Lima
spring.datasource.username=root
spring.datasource.password=0000

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=validate

# logging.level.org.springframework=DEBUG
# logging.level.org.hibernate.SQL=DEBUG
# logging.level.org.springframework.security=DEBUG
# logging.level.com.soft.ecommerce=DEBUG
stripe.secret.key = test