spring.application.name=backend

# LANGUAGE
spring.web.locale=en_US
spring.web.locale-resolver=fixed

# SPRING SECURITY
spring.security.user.name=${SPRING_SECURITY_USER_NAME}
spring.security.user.password=${SPRING_SECURITY_USER_PASSWORD}

# SERVICES
image.base.url=http://localhost:8080/images
project.image=images/
frontend.url=${FRONTEND_URL}

# JWT
spring.app.jwtSecret=${SPRING_APP_JWT_SECRET}
spring.app.jwtExpirationMs=${SPRING_APP_JWT_EXPIRATION_MS}
spring.ecom.app.jwtCookieName=${SPRING_ECOM_APP_JWT_COOKIE_NAME}

# MYSQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=validate

# logging.level.org.springframework=DEBUG
# logging.level.org.hibernate.SQL=DEBUG
# logging.level.org.springframework.security=DEBUG
# logging.level.com.soft.ecommerce=DEBUG
stripe.secret.key=${STRIPE_SECRET_KEY}